Repository Team-Hanbae/Hanbae-iOS, pull requests merged in 2024-12, with the labels that each got.

#307 [Refactor] #306 View에서 필요한 기능에 따른 ViewModel 분리
  Macro.xcodeproj/project.pbxproj
  Macro/Screen/BuiltInJangdanScreen/BuiltinJangdanPracticeView.swift
  Macro/Screen/BuiltInJangdanScreen/ViewModel/BuiltInJangdanPracticeViewModel.swift
  Macro/Screen/CustomJangdanListScreen/CustomJangdanCreateView.swift
  Macro/Screen/CustomJangdanListScreen/CustomJangdanPracticeView.swift
  Macro/Screen/CustomJangdanListScreen/ViewModel/CustomJangdanCreateViewModel.swift
  Macro/Screen/CustomJangdanListScreen/ViewModel/CustomJangdanListViewModel.swift
  Macro/Screen/CustomJangdanListScreen/ViewModel/CustomJangdanPracticeViewModel.swift
  Macro/Screen/HomeScreen/HomeView.swift
  Macro/Screen/MetronomeScreen/ViewModel/MetronomeViewModel.swift
  Macro/System/DIContainer.swift
  Macro/System/Router.swift
Labels: enhancement

#308 [Refactor] #153 프로젝트 청소
  Macro.xcodeproj/project.pbxproj
  Macro/Domain/Entity/JangdanEnum.swift
  Macro/Domain/UseCase/Interface/MasteryUseCase.swift
  Macro/Domain/UseCase/Interface/TemplateUseCase.swift
  Macro/Domain/UseCase/MasteryImplement.swift
  Macro/Domain/UseCase/Repository/JangdanRepository.swift
  Macro/Domain/UseCase/Repository/MastaryRepository.swift
  Macro/Domain/UseCase/TapTapImplement.swift
  Macro/Domain/UseCase/TemplateImplement.swift
  Macro/Screen/CustomJangdanListScreen/CustomJangdanCreateView.swift
  Macro/Screen/CustomJangdanListScreen/CustomJangdanPracticeView.swift
  Macro/Screen/CustomJangdanListScreen/JangdanTypeSelectView.swift
  Macro/Screen/HomeScreen/ViewModel/HomeViewModel.swift
  Macro/Screen/JangdanSelectScreen/JangdanSelectView.swift
  Macro/Screen/MetronomeScreen/BakBarSetView.swift
  Macro/Screen/MetronomeScreen/JangdanSelectSheetView.swift
  Macro/Screen/MetronomeScreen/MetronomeControlView.swift
  Macro/Screen/MetronomeScreen/ViewModel/MetronomeControlViewModel.swift
  Macro/Service/BasicJangdanData.swift
  Macro/Service/JangdanDataManager.swift
  Macro/Service/JangdanDataSource.swift
  Macro/Service/MasteryDataSource.swift
  Macro/Service/SoundManager.swift
  Macro/System/AppState.swift
  Macro/System/DIContainer.swift
Labels: enhancement, chore

#309 [Refactor] #303 NavigationLink를 Router로 대체
  Macro/Screen/HomeScreen/HomeView.swift
  Macro/System/Router.swift
Labels: enhancement

#312 [Fix] #311 재생 여부가 화면을 벗어나도 초기화되지 않는 오류
  Macro/Domain/UseCase/Interface/MetronomeOnOffUseCase.swift
  Macro/Domain/UseCase/MetronomeOnOffImplement.swift
  Macro/Screen/MetronomeScreen/MetronomeControlView.swift
  Macro/Screen/MetronomeScreen/MetronomeView.swift
  Macro/Screen/MetronomeScreen/ViewModel/MetronomeControlViewModel.swift
  Macro/Screen/MetronomeScreen/ViewModel/MetronomeViewModel.swift
  Macro/System/DIContainer.swift
Labels: bug, enhancement

#317 [Refactor] #316 북,장구 전체 소리 파일 변경
  Macro.xcodeproj/project.pbxproj
  Macro/Resources/Sound/buk_medium.wav
  Macro/Resources/Sound/buk_strong.wav
  Macro/Resources/Sound/buk_weak.wav
  Macro/Resources/Sound/jangu_medium.wav
  Macro/Resources/Sound/jangu_strong.wav
  Macro/Resources/Sound/jangu_weak.wav
Labels: enhancement

#318 [Fix] #313 isSobakOn 공유되지 않던 문제
  Macro/Domain/UseCase/Interface/MetronomeOnOffUseCase.swift
  Macro/Domain/UseCase/MetronomeOnOffImplement.swift
  Macro/Screen/MetronomeScreen/ViewModel/MetronomeViewModel.swift
Labels: bug

#320 [Chore] #319 암호화 알고리즘 사용 여부를 설정합니다
  Macro.xcodeproj/project.pbxproj
  Macro/Info.plist
Labels: chore

#321 [Chore] 릴리즈 생성용 PR
  Macro.xcodeproj/project.pbxproj
  Macro/Domain/UseCase/Interface/MetronomeOnOffUseCase.swift
  Macro/Domain/UseCase/MetronomeOnOffImplement.swift
  Macro/Info.plist
  Macro/Resources/Sound/buk_medium.wav
  Macro/Resources/Sound/buk_strong.wav
  Macro/Resources/Sound/buk_weak.wav
  Macro/Resources/Sound/jangu_medium.wav
  Macro/Resources/Sound/jangu_strong.wav
  Macro/Resources/Sound/jangu_weak.wav
  Macro/Screen/MetronomeScreen/MetronomeControlView.swift
  Macro/Screen/MetronomeScreen/MetronomeView.swift
  Macro/Screen/MetronomeScreen/ViewModel/MetronomeControlViewModel.swift
  Macro/Screen/MetronomeScreen/ViewModel/MetronomeViewModel.swift
  Macro/System/DIContainer.swift
Labels: enhancement
