Repository Team-Hanbae/Hanbae-iOS, pull requests merged in 2025-07, with the labels that each got.

#442 [Feat] #441 신규 뱃지 애니메이션 수정
  Macro/Screen/MetronomeScreen/MetronomeControlView.swift
Labels: enhancement, design

#451 [feat] #450 배너 교체
  Macro/Resources/Asset/Assets.xcassets/Banner/JeongakBanner.imageset/Contents.json
  Macro/Resources/Asset/Assets.xcassets/Banner/JeongakBanner.imageset/KakaoTalk_Photo_2025-07-18-02-06-07 1.png
  Macro/Resources/Asset/Assets.xcassets/Banner/JeongakBanner.imageset/KakaoTalk_Photo_2025-07-18-02-06-07 2.png
  Macro/Resources/Asset/Assets.xcassets/Banner/JeongakBanner.imageset/KakaoTalk_Photo_2025-07-18-02-06-07.png
  Macro/Screen/HomeScreen/HomeView.swift
Labels: enhancement

#447 [Fix] #446 Blink 기능 복구
  Macro/Screen/HomeScreen/HomeView.swift
Labels: bug

#457 [Fix] #456 메트로놈 컨트롤러 UI
  Macro/Screen/MetronomeScreen/MetronomeControlView.swift
Labels: bug

#455 [Fix] #454 장단 삭제시 홈화면 상단 네비바 이슈
  Macro/Screen/CustomJangdanListScreen/CustomJangdanPracticeView.swift
Labels: bug

#459 [Release] #458 ver 2.5.3
  Macro.xcodeproj/project.pbxproj
Labels: chore

#461 [Fix] #460 키보드 출현시 화면 밀려올라가는 이슈
  Macro/Screen/MetronomeScreen/MetronomeView.swift
Labels: bug

#468 [Release] #467 ver 2.6.0
  Macro.xcodeproj/project.pbxproj
Labels: release
