Repository Team-Hanbae/Hanbae-iOS, pull requests merged in 2025-01, with the labels that each got.

#323 [Refactor] #322 private 변수 가독성 향상
  Macro/Screen/BuiltInJangdanScreen/ViewModel/BuiltInJangdanPracticeViewModel.swift
  Macro/Screen/CustomJangdanListScreen/ViewModel/CustomJangdanCreateViewModel.swift
  Macro/Screen/CustomJangdanListScreen/ViewModel/CustomJangdanListViewModel.swift
  Macro/Screen/CustomJangdanListScreen/ViewModel/CustomJangdanPracticeViewModel.swift
  Macro/Screen/MetronomeScreen/ViewModel/MetronomeControlViewModel.swift
  Macro/Screen/MetronomeScreen/ViewModel/MetronomeViewModel.swift
  Macro/System/AppState.swift
  Macro/System/DIContainer.swift
Labels: enhancement

#325 [Test] #324 앱 진입점에 이상한거 있길래 지워봤습니다.
  Macro.xcodeproj/project.pbxproj
  Macro/System/MacroApp.swift
  MacroTests/TempoUseCaseTests.swift
  MacroUITests/MacroUITests.swift
  MacroUITests/MacroUITestsLaunchTests.swift
Labels: enhancement, test

#327 Revert "[Test] #324 앱 진입점에 이상한거 있길래 지워봤습니다."
  Macro.xcodeproj/project.pbxproj
  Macro/System/MacroApp.swift
  MacroTests/TempoUseCaseTests.swift
  MacroUITests/MacroUITests.swift
  MacroUITests/MacroUITestsLaunchTests.swift
Labels: chore

#331 [Feat] #328 한배 설문조사 배너 설정
  Macro/Resources/Asset/Assets.xcassets/Banner/Contents.json
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/Contents.json
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/SurveyBanner 1.png
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/SurveyBanner 2.png
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/SurveyBanner.png
  Macro/Screen/HomeScreen/HomeView.swift
Labels: enhancement

#335 [Design] #334 설문조사 배너 디자인 변경
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/SurveyBanner 1.png
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/SurveyBanner 2.png
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/SurveyBanner.png
  Macro/Screen/HomeScreen/HomeView.swift
Labels: enhancement, design

#333 [Feat] #329 Dynamic Icon
  Macro.xcodeproj/project.pbxproj
  Macro/Domain/UseCase/DynamicIconImplement.swift
  Macro/Domain/UseCase/Interface/DynamicIconUseCase.swift
  Macro/Extensions/Date+Extension.swift
  Macro/Info.plist
  Macro/Resources/Icon/NewYear@2x.png
  Macro/Resources/Icon/NewYear@3x.png
  Macro/Screen/HomeScreen/HomeView.swift
  Macro/Screen/HomeScreen/ViewModel/HomeViewModel.swift
  Macro/System/DIContainer.swift
  Macro/System/MacroApp.swift
Labels: enhancement

#337 [Release] #336 ver 2.2.1
  Macro.xcodeproj/project.pbxproj
  Macro/Domain/UseCase/DynamicIconImplement.swift
  Macro/Domain/UseCase/Interface/DynamicIconUseCase.swift
  Macro/Extensions/Date+Extension.swift
  Macro/Info.plist
  Macro/Resources/Asset/Assets.xcassets/Banner/Contents.json
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/Contents.json
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/SurveyBanner 1.png
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/SurveyBanner 2.png
  Macro/Resources/Asset/Assets.xcassets/Banner/SurveyBanner.imageset/SurveyBanner.png
  Macro/Resources/Icon/NewYear@2x.png
  Macro/Resources/Icon/NewYear@3x.png
  Macro/Screen/HomeScreen/HomeView.swift
  Macro/Screen/HomeScreen/ViewModel/HomeViewModel.swift
  Macro/System/DIContainer.swift
  Macro/System/MacroApp.swift
Labels: release

#339 [Fix] #338 뉴스가판대 관련 설정 삭제
  Macro/Info.plist
Labels: bug

#340 [Fix] #338 뉴스가판대 관련 설정 제거
  Macro/Info.plist
Labels: bug

#342 [Fix] #341 에셋 사이즈 변경
  Macro/Resources/Icon/NewYear@2x.png
  Macro/Resources/Icon/NewYear@3x.png
Labels: bug

#343 [Fix] #341 에셋 사이즈 변경
  Macro/Resources/Icon/NewYear@2x.png
  Macro/Resources/Icon/NewYear@3x.png
Labels: bug

#345 [Fix] #344 아이콘 변경 오류
  Macro/System/MacroApp.swift
Labels: bug

#346 [Chore] #344 v2.2.2 버전 넘버 변경
  Macro.xcodeproj/project.pbxproj
Labels: chore

#348 [Release] #347 ver 2.2.2
  Macro.xcodeproj/project.pbxproj
  Macro/System/MacroApp.swift
Labels: release

#350 [Fix] #349 아이콘 변경 이슈 2
  Macro.xcodeproj/project.pbxproj
  Macro/Resources/Icon/NewYear@3x.png
Labels: bug, chore

#359 [Fix] #358 블루투스 연결 시 소리 재생이 안되는 문제 해결
  Macro/Service/SoundManager.swift
Labels: bug

#360 [Feat] #332 인앱 리뷰 요청 기능 구현
  Macro/Screen/CustomJangdanListScreen/CustomJangdanCreateView.swift
  Macro/Screen/CustomJangdanListScreen/CustomJangdanListView.swift
  Macro/Screen/HomeScreen/HomeView.swift
  Macro/System/AppState.swift
Labels: enhancement

#364 [feat] #361 장구 음원파일 변경
  Macro.xcodeproj/project.pbxproj
  Macro/Resources/Sound/jangu_medium.wav
  Macro/Resources/Sound/jangu_strong.wav
  Macro/Resources/Sound/jangu_weak.wav
Labels: enhancement, chore

#368 [Docs] #353 개발 프로세스 문서 업데이트
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/other-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  Docs/README.md
Labels: documentation

#373 [Pre-Release] #372 ver 2.4.0
  Macro.xcodeproj/project.pbxproj
Labels: release
